/**
 * @module dsh-cordis
 * @description adw 专属 dsh 运行时组装配置（cordis.yml）生成器
 *
 * 生成的组成逐行对齐 dsh 官方 examples/jsonrpc-agent/cordis.yml（rc.6），
 * 差异仅有三处参数化：工作目录、会话持久化根目录、技能注入目录。
 * spine（llm/session/system-prompt/tools/agent/agent-loop/invariants 等
 * 十余个插件的装配）由官方聚合包 @deepseek-ai/dsh-agent-spine-demo 承担，
 * 避免手工罗列子条目（曾因缺少 invariants 服务提供者导致 4 个 /invariant
 * 条目挂起，见 spine-demo 源码 apply() 的装载顺序）。
 *
 * ⚠️ 部署铁律：stdout 保留给 JSON-RPC 协议，任何插件不得向 stdout 打日志。
 */

import {pathToFileURL} from 'node:url';

/** 单个 MCP 服务器（stdio 传输）配置 */
export interface DshMcpServerConfig {
    command: string;
    args: string[];
    env?: Record<string, string>;
}

/** 组装选项 */
export interface DshCordisOptions {
    /** agent 工作目录（bash/fs 的 cwd） */
    cwd: string;
    /** 会话持久化根目录（append-only JSONL 落盘处） */
    sessionRoot: string;
    /** dsh home（技能/凭据等共享目录，spine 必填字段） */
    dshHome: string;
    /** 部署人格（system-prompt 的 persona） */
    persona?: string;
    /** bash 工具超时（毫秒，默认 60s 对齐官方示例） */
    bashTimeoutMs?: number;
    /** 技能注入目录（含 <name>/SKILL.md 子目录）；缺省不挂载技能栈 */
    skillsDir?: string;
    /** MCP 服务器（stdio）；键为服务器名 */
    mcpServers?: Record<string, DshMcpServerConfig>;
    /**
     * SDK 服务器插件（绝对路径）。缺省用官方 @deepseek-ai/dsh-sdk-jsonrpc-server；
     * adw 生产路径传 runtime-dsh/sdk-server.mjs（resume 感知版：create 撞上
     * 磁盘持久化日志时自动降级 agents.resume，支持跨进程续接会话）。
     */
    serverPluginPath?: string;
}

/** 默认人格：对齐官方示例语气，强调 adw 的自动化定位 */
export const DEFAULT_PERSONA =
    'You are a coding agent working inside AI Dev Workbench. Prefer minimal, surgical changes and always verify your work.';

/** YAML 双引号标量（JSON.stringify 转义与 YAML 双引号语法兼容且反斜杠安全） */
function q(s: string): string {
    return JSON.stringify(s);
}

/**
 * 插件路径 -> ESM 可导入的 specifier。
 * cordis loader 的入口名最终走裸动态 import：Windows 盘符绝对路径会被
 * ESM 判为 'd:' 协议拒绝（ERR_UNSUPPORTED_ESM_URL_SCHEME），
 * 必须 file:// URL 形式。
 */
function pluginSpecifier(p: string): string {
    return pathToFileURL(p).href;
}

/** YAML 双引号数组 */
function qa(items: string[]): string {
    return `[${items.map(q).join(', ')}]`;
}

/**
 * 生成 cordis.yml 文本。
 * 内容是确定性的：相同选项产出相同文本（便于内容 hash 命名与复用）。
 */
export function buildCordisYml(options: DshCordisOptions): string {
    const {cwd, sessionRoot, dshHome} = options;
    const persona = options.persona?.trim() || DEFAULT_PERSONA;
    const bashTimeoutMs = options.bashTimeoutMs ?? 60_000;
    const lines: string[] = [];

    lines.push('# Generated by adw dsh-provider (buildCordisYml). Do not edit by hand.');
    lines.push('# Composition mirrors dsh examples/jsonrpc-agent/cordis.yml @ 0.1.0-rc.6.');
    lines.push('# stdout is reserved for JSON-RPC; do not add console loggers or terminal UI.');
    lines.push('');

    // --- SDK 服务器：stdin/stdout JSON-RPC 2.0 ---
    // （adw 用 resume 感知子类插件；loader 入口名须为 file:// URL——
    //   Windows 绝对路径会被裸动态 import 当作 'd:' 协议拒绝）
    const serverName = options.serverPluginPath
        ? pluginSpecifier(options.serverPluginPath)
        : '@deepseek-ai/dsh-sdk-jsonrpc-server';
    lines.push('- id: sdk-jsonrpc-server');
    lines.push(`  name: ${q(serverName)}`);
    lines.push('  config:');
    lines.push('    maxTokensAsSuccess: true');
    lines.push('');

    // --- LLM 适配器：DeepSeek 官方端点；模型经 initialize 按会话指定 ---
    lines.push('- id: llm-deepseek');
    lines.push(`  name: '@deepseek-ai/dsh-llm-deepseek'`);
    lines.push('  config:');
    lines.push('    thinking: enabled');
    lines.push('    reasoningEffort: max');
    lines.push('');

    // --- bash 执行器底座 ---
    lines.push('- id: subprocess');
    lines.push(`  name: '@deepseek-ai/dsh-subprocess-local'`);
    lines.push('');
    lines.push('- id: bash');
    lines.push(`  name: '@deepseek-ai/dsh-bash-local'`);
    lines.push('  config:');
    lines.push(`    cwd: ${q(cwd)}`);
    lines.push(`    timeoutMs: ${bashTimeoutMs}`);
    lines.push('');

    // --- agent spine：官方聚合（timer/llm/session/title/system-prompt/tools/ -->
    // --- skills/agent/llm-retry/jobs/invariants+4伴随/tools-bash/agent-loop） ---
    lines.push('- id: agent-spine');
    lines.push(`  name: '@deepseek-ai/dsh-agent-spine-demo'`);
    lines.push('  config:');
    lines.push(`    dshHome: ${q(dshHome)}`);
    lines.push(`    persona: ${q(persona)}`);
    lines.push('    workspaceContext: false');
    lines.push('    goals: false');
    if (options.skillsDir) {
        lines.push('    skills:');
        lines.push('      enabled: true');
        lines.push('      filesystem:');
        lines.push('        includeDefaultRoots: false');
        lines.push(`        agentsHome: ${q(dshHome)}`);
        lines.push(`        customSkillDirs: ${qa([options.skillsDir])}`);
    } else {
        lines.push('    skills:');
        lines.push('      enabled: false');
    }
    lines.push('    toolBash:');
    lines.push('      enableRunInBackground: false');
    lines.push('    toolJobs: false');
    lines.push('');

    // --- 会话持久化：append-only JSONL，adw 侧只读投影 ---
    lines.push('- id: sessions');
    lines.push(`  name: '@deepseek-ai/dsh-session-persistence-jsonl'`);
    lines.push('  config:');
    lines.push(`    root: ${q(sessionRoot)}`);
    lines.push("    compression: 'none'");
    lines.push('');

    // --- 模型请求前检查点（崩溃恢复） ---
    lines.push('- id: session-checkpoints');
    lines.push(`  name: '@deepseek-ai/dsh-session-checkpoint-policy'`);
    lines.push('');

    // --- 子代理：进程内 spawn，Task 工具委托 ---
    lines.push('- id: subagent');
    lines.push(`  name: '@deepseek-ai/dsh-subagent'`);
    lines.push('');
    lines.push('- id: subagent-spawn-in-process');
    lines.push(`  name: '@deepseek-ai/dsh-subagent-spawn-in-process'`);
    lines.push('  config:');
    lines.push(`    providerName: ${q('spawn')}`);
    lines.push('');
    lines.push('- id: tool-subagent');
    lines.push(`  name: '@deepseek-ai/dsh-tool-subagent'`);
    lines.push('  config:');
    lines.push(`    provider: ${q('spawn')}`);
    lines.push(`    toolName: ${q('subagent')}`);
    lines.push('    enableRunInBackground: false');
    lines.push('');

    // --- 任务清单工具 ---
    lines.push('- id: tool-todo');
    lines.push(`  name: '@deepseek-ai/dsh-tool-todo'`);
    lines.push('  config:');
    lines.push('    allowParallelInProgress: true');
    lines.push('');

    // --- 文件系统（本地直连 + 观察策略 + 工具） ---
    lines.push('- id: fs-local');
    lines.push(`  name: '@deepseek-ai/dsh-fs-local'`);
    lines.push('  config:');
    lines.push(`    cwd: ${q(cwd)}`);
    lines.push('');
    lines.push('- id: fs-observation-policy');
    lines.push(`  name: '@deepseek-ai/dsh-fs-observation-policy'`);
    lines.push('');
    lines.push('- id: tool-fs');
    lines.push(`  name: '@deepseek-ai/dsh-tool-fs'`);
    lines.push('');

    // --- token 计量 + 上下文压实 ---
    lines.push('- id: token-meter');
    lines.push(`  name: '@deepseek-ai/dsh-token-meter'`);
    lines.push('');
    lines.push('- id: compaction-basic');
    lines.push(`  name: '@deepseek-ai/dsh-compaction-basic'`);
    lines.push('  config:');
    lines.push('    thresholdRatio: 0.8');
    lines.push('    retainRatio: 0.16');
    lines.push('    maxTokens: 8192');
    lines.push('    compactionRetries: 1');
    lines.push('');

    // --- MCP 服务器：每台一行（stdio 传输） ---
    const mcpEntries = Object.entries(options.mcpServers ?? {}).sort(([a], [b]) => a.localeCompare(b));
    for (const [name, server] of mcpEntries) {
        lines.push(`- id: mcp-${name}`);
        lines.push(`  name: '@deepseek-ai/dsh-mcp-client'`);
        lines.push('  config:');
        lines.push(`    transport: ${q('stdio')}`);
        lines.push(`    serverName: ${q(name)}`);
        lines.push(`    command: ${q(server.command)}`);
        lines.push(`    args: ${qa(server.args)}`);
        if (server.env && Object.keys(server.env).length > 0) {
            lines.push(`    env: ${JSON.stringify(server.env)}`);
        }
        lines.push('');
    }

    return lines.join('\n');
}
